import 'models/training.dart';

List<Training> training = [
  new Training(
    'IT Internship - Alexandria',
    'assets/images/company/company1.png',
    'Blue Academy',
    'posted 3 days ago',
    'Alexandria Egypt',
    'A chance to further develop strong communication, teamwork, and problem-solving skills',
    'Fresh Graduate,Alexandria residency, Engineering degree, Good knowledge of computers and networking, CCNA training is preferred',
    'paid',
    'one open vacancy',
  ),
  new Training(
    "HR Recruitment Internship",
    "assets/images/company/company2.png",
    "Blue Academy",
    "posted 4 days ago",
    "Alexandria Egypt",
    "Working In Startup Environment will let you gain experience",
    "Fresh Graduate,Alexandria residency, Accounting degree, Good knowledge of computers and networking, CCNA training is preferred",
    "1000",
    "Two open vacancies",
  ),
  new Training(
    "Front-End Development",
    "assets/images/company/company3.jpg",
    "M Eight",
    "3 days ago",
    "6th of October",
    "If you are a Talented front end developer , or have a background about it, and you willing to learn more about the field,  so you're must welcome to join our team,",
    "0 to 1 years Bachelor's Degree is plus, Excellent HTML5 and CSS3, Programming skills : Good JavaScript knowledge. React.js is a plus, Experience building for Responsive Design ,Work with back end development team to integrate the front end with back end, Familiar knowledge of JavaScript,html, css  preprocessors (sass,scss)",
    "1000",
    "Two open vacancies",
  ),
  new Training(
    "Business Development",
    "assets/images/company/company4.png",
    "HLPR",
    "2 days ago",
    "Maadi, Cairo",
    "Working In Startup Environment will let you gain experience",
    "Fresh Graduate,Alexandria residency, Accounting degree, Good knowledge of computers and networking, CCNA training is preferred",
    "1000",
    "Two open vacancies",
  ),
  new Training(
    'IT Internship - Alexandria',
    'assets/images/company/company1.png',
    'Blue Academy',
    'posted 3 days ago',
    'Alexandria Egypt',
    'A chance to further develop strong communication, teamwork, and problem-solving skills',
    'Fresh Graduate,Alexandria residency, Engineering degree, Good knowledge of computers and networking, CCNA training is preferred',
    'paid',
    'one open vacancy',
  ),
  new Training(
    "HR Recruitment Internship",
    "assets/images/company/company2.png",
    "Blue Academy",
    "posted 4 days ago",
    "Alexandria Egypt",
    "Working In Startup Environment will let you gain experience",
    "Fresh Graduate,Alexandria residency, Accounting degree, Good knowledge of computers and networking, CCNA training is preferred",
    "1000",
    "Two open vacancies",
  ),
];
