import 'models/training.dart';

List<Training> training = [
  new Training(
    'front end',
    'tanta',
    'media gate',
    'ps skills',
    '2 months',
    '2 vacancies',
    'html, css',
    'fresh gradusted',
    'web design',
  ),
  new Training(
    'front end',
    'tanta',
    'media gate',
    'ps skills',
    '2 months',
    '2 vacancies',
    'html, css',
    'fresh gradusted',
    'web design',
  ),
  new Training(
    'front end',
    'tanta',
    'media gate',
    'ps skills',
    '2 months',
    '2 vacancies',
    'html, css',
    'fresh gradusted',
    'web design',
  ),
  new Training(
    'front end',
    'tanta',
    'media gate',
    'ps skills',
    '2 months',
    '2 vacancies',
    'html, css',
    'fresh gradusted',
    'web design',
  ),
  new Training(
    'back end',
    'tanta',
    'media gate',
    'ps skills',
    '2 months',
    '2 vacancies',
    'html, css',
    'fresh gradusted',
    'web design',
  ),
  new Training(
    'back end',
    'tanta',
    'media gate',
    'ps skills',
    '2 months',
    '2 vacancies',
    'html, css',
    'fresh gradusted',
    'web design',
  ),
];
